name: "Python Linters"

description: "Lint Python code the same way everywhere in Datawiz.io"

author: "Datawiz.io"

inputs:
  black-options:
    description: "Additional options to pass to run `black` with"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.black-options }}