name: Docker Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: flake8
        uses: ./.github/actions/flake8

      - name: isort
        uses: ./.github/actions/isort

